---
# debian_gnu_linux_bookworm.yml
#
- hosts: 127.0.0.1
  connection: local

- name: Install apt packages
  import_playbook: general/apt-packages-debian_gnu_linux_bookworm.yml

- name: Oh My ZSH Setup
  import_playbook: oh-my-zsh/debian_gnu_linux_bookworm.yml

- name: ASDF Setup
  import_playbook: asdf/debian_gnu_linux_bookworm.yml

- name: ASDF
  import_playbook: asdf/debian_gnu_linux_bookworm.yml

- name: Krew Plugin install
  import_playbook: krew/debian_gnu_linux_bookworm.yml
