---
- hosts: 127.0.0.1
  connection: local

- name: Importing git repos playbook
  import_playbook: general/packages.yml

- name: Oh My ZSH Setup
  import_playbook: oh-my-zsh/ubuntu_jammy.yml

- name: ASDF Setup
  import_playbook: asdf/ubuntu_jammy.yml

- name: ASDF
  import_playbook: asdf/asdf_packages.yml

- name: Docker Setup
  import_playbook: docker/ubuntu_jammy.yml

    #- name: AWS VPN Client Setup
    #  import_playbook: aws-vpn-client/ubuntu_jammy.yml
