---
- hosts: 127.0.0.1
  connection: local

- name: Install atp packages
  import_playbook: general/apt-packages.yml

- name: Install snap packages
  import_playbook: general/snap-packages.yml

- name: Oh My ZSH Setup
  import_playbook: oh-my-zsh/ubuntu_jammy.yml

- name: ASDF Setup
  import_playbook: asdf/ubuntu_jammy.yml

- name: ASDF
  import_playbook: asdf/asdf_packages.yml

- name: Docker Setup
  import_playbook: docker/ubuntu_jammy.yml

- name: Powershell Setup
  import_playbook: powershell/ubuntu_jammy.yml

- name: VIM Setup
  import_playbook: vim/ubuntu_jammy.yml

- name: Krew Plugin install
  import_playbook: krew/ubuntu_jammy.yml

- name: Atlas cli install
  import_playbook: atlas-cli/ubuntu_jammy.yml

- name: amazon-ec2-instance-selector install
  import_playbook: amazon-ec2-instance-selector/ubuntu_jammy.yml

    #- name: AWS VPN Client Setup
    #  import_playbook: aws-vpn-client/ubuntu_jammy.yml
- name: Quickemu setup
  import_playbook: quickemu/ubuntu_jammy.yml
